### ISSUE TITLE
Writing to GBQ? And Fix for Column Type [Any]?

### ISSUE THREAD

**Issue by WilliamZimmerman83** [martineastwood/GBQ#9]
1. Is there a way to write a data frame to GBQ using this package (can you provide an example?) 
2. Is there a way to read the column types rather than just getting type [Any]?

The ease of use and setup has been great for analysis and running models - but now I would like to get the results back into BQ without having to export CSVs etc.

**Comment by ChaimKesler** [comment]
@WilliamZimmerman83 Thanks for flagging that this might be an issue for others.
I started a branch locally and I can open a PR this week for bullet 2 with some of the code from here:
https://github.com/ChaimKesler/julia_toolbox/blob/main/BigQueryPipe.jl

I'm thinking of making my function `_basic_type_converter` an optional parameter so the dataframe only gets passed through the function if the types aren't getting processed correctly (rather than each time, for efficiency). Curious to hear thoughts on that front. Also, I only had issues with Int and Float, so I only pulled those in for my purposes since String is the default when falling to get parsed. But, let me know if there are other datatypes we should be checking for and I can include them.

I will also a PR if #1 is still open after I work it through on my end.

**Comment by ChaimKesler** [comment]
@WilliamZimmerman83  and @martineastwood  I opened a PR here: https://github.com/martineastwood/GBQ/pull/10

I kept this close to the way GBQ.jl was written (rather than using JSONtables or JSON modules like in my example above).

I tested this locally a few times and worked on julia 1.7. Only added to the query pull.

**Comment by ChaimKesler** [comment]
I started a Topic in Julia Discourse on loading dataframes:
https://discourse.julialang.org/t/loading-dataframes-into-big-query/95457

**Comment by WilliamZimmerman83** [comment]
So here is a potential solution I have been working on:

```
function randstring(length::Int=8)
    alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
    randstring = ""
    for i in 1:length
        randstring *= alphabet[rand(1:end)]
    end
    return randstring
end

function gbq_upload(df::DataFrame, project::AbstractString, dataset::AbstractString, table::AbstractString)
    # write to temporary CSV file
    temp_file = joinpath(tempdir(), randstring() * ".csv")
    CSV.write(temp_file, df)
    
    # build command to upload CSV to BigQuery
    cmd = `bq load --quiet=true --project_id=$project --skip_leading_rows=1 --source_format=CSV $dataset.$table $temp_file`
    
    # run command and capture output
    output = read(cmd, String)
    
    # delete temporary file
    rm(temp_file)
    
    return output
end

```
I then tested this out with: 

```
using Pkg

using GBQ, DataFrames, CSV

# assume we have a DataFrame called df that we want to upload to a BigQuery table called my_table in my_dataset
project_id = "xxxx"
dataset_id = "xxxx"
table_id = "xxxx"

df = DataFrame(a = [1, 2, 3], b = ["x", "y", "z"])

gbq_upload(df, project_id, dataset_id, table_id)

```
This uploads the data correctly to the table. Can you test this and see if it works on your end?

**Comment by WilliamZimmerman83** [comment]
Next couple of steps in my mind for testing is:

- What are the limitations of this approach/ is there something more efficient (JSON instead of CSV?)
- Can we fix this approach to create the table and not just upload to it (it just currently does a 'dumb' append -  is there a way to make this optionally incremental OR just wipe the table and upload the data?

**Comment by martineastwood** [comment]
Thanks for highlighting this, unfortunately I don't have access to BigQuery at the moment so am unable to test on my end

**Comment by WilliamZimmerman83** [comment]
Closing this as I've scripted the edits and it works for JSON so we can keep this lightweight.

**Comment by WilliamZimmerman83** [comment]
Closing this as I've scripted the edits and it works for JSON so we can keep this lightweight.
